# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(974, 600)
        MainWindow.setMinimumSize(QtCore.QSize(974, 594))
        MainWindow.setStyleSheet("background-color: rgb(8, 1, 28);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 6)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setStyleSheet("QFrame {\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 25px;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.email_pushButton_15 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.email_pushButton_15.setFont(font)
        self.email_pushButton_15.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    background-color: rgb(182, 96, 88);\n"
"\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/icons8-gmail-logo-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.email_pushButton_15.setIcon(icon)
        self.email_pushButton_15.setIconSize(QtCore.QSize(35, 35))
        self.email_pushButton_15.setObjectName("email_pushButton_15")
        self.gridLayout_11.addWidget(self.email_pushButton_15, 0, 0, 1, 1)
        self.google_pushButton_14 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.google_pushButton_14.setFont(font)
        self.google_pushButton_14.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    background-color: rgb(211, 211, 211);\n"
"\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/icons8-google-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.google_pushButton_14.setIcon(icon1)
        self.google_pushButton_14.setIconSize(QtCore.QSize(35, 35))
        self.google_pushButton_14.setObjectName("google_pushButton_14")
        self.gridLayout_11.addWidget(self.google_pushButton_14, 1, 0, 1, 1)
        self.face_pushButton_13 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.face_pushButton_13.setFont(font)
        self.face_pushButton_13.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(156, 232, 255);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    background-color: rgb(103, 194, 255);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/icons8-facebook-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.face_pushButton_13.setIcon(icon2)
        self.face_pushButton_13.setIconSize(QtCore.QSize(35, 35))
        self.face_pushButton_13.setObjectName("face_pushButton_13")
        self.gridLayout_11.addWidget(self.face_pushButton_13, 2, 0, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    background-color: rgb(211, 211, 211);\n"
"\n"
"}\n"
"\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/icons8-youtube-logo-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon3)
        self.pushButton_12.setIconSize(QtCore.QSize(35, 35))
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_11.addWidget(self.pushButton_12, 3, 0, 1, 1)
        self.tiktok_pushButton_11 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.tiktok_pushButton_11.setFont(font)
        self.tiktok_pushButton_11.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(140, 140, 140);\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/icons8-tiktok-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tiktok_pushButton_11.setIcon(icon4)
        self.tiktok_pushButton_11.setIconSize(QtCore.QSize(35, 35))
        self.tiktok_pushButton_11.setObjectName("tiktok_pushButton_11")
        self.gridLayout_11.addWidget(self.tiktok_pushButton_11, 4, 0, 1, 1)
        self.insta_pushButton_10 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.insta_pushButton_10.setFont(font)
        self.insta_pushButton_10.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(220, 220, 220);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    background-color: rgb(211, 211, 211);\n"
"\n"
"}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/icons8-instagram-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.insta_pushButton_10.setIcon(icon5)
        self.insta_pushButton_10.setIconSize(QtCore.QSize(40, 40))
        self.insta_pushButton_10.setObjectName("insta_pushButton_10")
        self.gridLayout_11.addWidget(self.insta_pushButton_10, 5, 0, 1, 1)
        self.start_pushButton_9 = QtWidgets.QPushButton(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.start_pushButton_9.setFont(font)
        self.start_pushButton_9.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    background-color: rgb(211, 211, 211);\n"
"\n"
"}\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/icons8-circled-play-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start_pushButton_9.setIcon(icon6)
        self.start_pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.start_pushButton_9.setObjectName("start_pushButton_9")
        self.gridLayout_11.addWidget(self.start_pushButton_9, 6, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_6, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_3, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Acceuil = QtWidgets.QWidget()
        self.Acceuil.setObjectName("Acceuil")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.Acceuil)
        self.gridLayout_10.setContentsMargins(35, 35, 35, 35)
        self.gridLayout_10.setSpacing(35)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gif_label_3 = QtWidgets.QLabel(self.Acceuil)
        self.gif_label_3.setText("")
        self.gif_label_3.setPixmap(QtGui.QPixmap("images/Gif/AI visualization design.gif"))
        self.gif_label_3.setScaledContents(False)
        self.gif_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.gif_label_3.setWordWrap(False)
        self.gif_label_3.setObjectName("gif_label_3")
        self.gridLayout_10.addWidget(self.gif_label_3, 0, 0, 1, 1)
        self.message_list = QtWidgets.QTextBrowser(self.Acceuil)
        self.message_list.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(212, 212, 212);\n"
"font: 75 10pt \"Arial\";\n"
"border-radius:15px;")
        self.message_list.setObjectName("message_list")
        self.gridLayout_10.addWidget(self.message_list, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.Acceuil)
        self.Mores = QtWidgets.QWidget()
        self.Mores.setObjectName("Mores")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.Mores)
        self.gridLayout_12.setContentsMargins(6, 0, 12, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.frame_10 = QtWidgets.QFrame(self.Mores)
        self.frame_10.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_11 = QtWidgets.QFrame(self.frame_10)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.lampe_pushButton_16 = QtWidgets.QPushButton(self.frame_11)
        self.lampe_pushButton_16.setMinimumSize(QtCore.QSize(220, 41))
        self.lampe_pushButton_16.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lampe_pushButton_16.setFont(font)
        self.lampe_pushButton_16.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.lampe_pushButton_16.setObjectName("lampe_pushButton_16")
        self.gridLayout_14.addWidget(self.lampe_pushButton_16, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.frame_11, 0, 0, 1, 1)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_12)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_15.addWidget(self.label_4, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_13.addWidget(self.frame_12, 1, 0, 1, 1)
        self.gridLayout_12.addWidget(self.frame_10, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Mores)
        self.Commandes = QtWidgets.QWidget()
        self.Commandes.setObjectName("Commandes")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.Commandes)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.frame_13 = QtWidgets.QFrame(self.Commandes)
        self.frame_13.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_13)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_15)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 115))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_20.setSpacing(0)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_25.setMinimumSize(QtCore.QSize(60, 51))
        self.pushButton_25.setMaximumSize(QtCore.QSize(60, 51))
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"background-color: transparent;\n"
"color: #fffff;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"border-radius:8px;\n"
"    background-color: rgb(211, 211, 211);\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_25.setText("")
        self.pushButton_25.setIcon(icon6)
        self.pushButton_25.setIconSize(QtCore.QSize(45, 45))
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_20.addWidget(self.pushButton_25, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_16)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(250, 35))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(250, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"border-color:2px #3cfff9;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_20.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.gridLayout_18.addWidget(self.frame_16, 0, 0, 1, 1)
        self.gridLayout_17.addWidget(self.frame_15, 1, 0, 1, 1)
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMinimumSize(QtCore.QSize(0, 275))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_17.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_17.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_19.addWidget(self.pushButton_17, 0, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_18.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_18.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_19.addWidget(self.pushButton_18, 0, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_22.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_22.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_19.addWidget(self.pushButton_22, 1, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_19.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_19.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_19.addWidget(self.pushButton_19, 1, 1, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_23.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_23.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_19.addWidget(self.pushButton_23, 2, 0, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_24.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_24.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_19.addWidget(self.pushButton_24, 2, 1, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_27.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_27.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_19.addWidget(self.pushButton_27, 3, 0, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_26.setMinimumSize(QtCore.QSize(191, 41))
        self.pushButton_26.setMaximumSize(QtCore.QSize(191, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_19.addWidget(self.pushButton_26, 3, 1, 1, 1)
        self.gridLayout_17.addWidget(self.frame_14, 0, 0, 1, 1)
        self.gridLayout_16.addWidget(self.frame_13, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Commandes)
        self.About = QtWidgets.QWidget()
        self.About.setObjectName("About")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.About)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_17 = QtWidgets.QFrame(self.About)
        self.frame_17.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.frame_17)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_5 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_23.addWidget(self.label_5, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.frame_17, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.About)
        self.Contact = QtWidgets.QWidget()
        self.Contact.setObjectName("Contact")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.Contact)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.frame_18 = QtWidgets.QFrame(self.Contact)
        self.frame_18.setStyleSheet("background-color: rgb(199, 199, 199);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_3 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_24.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.frame_18, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Contact)
        self.gridLayout_4.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_5, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setMinimumSize(QtCore.QSize(0, 100))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.voulume_moins_pushButton_5 = QtWidgets.QPushButton(self.frame_8)
        self.voulume_moins_pushButton_5.setMinimumSize(QtCore.QSize(51, 41))
        self.voulume_moins_pushButton_5.setMaximumSize(QtCore.QSize(51, 41))
        self.voulume_moins_pushButton_5.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: transparent;\n"
"border-color:none;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(199, 199, 199);\n"
"borde-color:none;\n"
"border-radius:10px;\n"
"}")
        self.voulume_moins_pushButton_5.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/icons8-voice-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voulume_moins_pushButton_5.setIcon(icon7)
        self.voulume_moins_pushButton_5.setIconSize(QtCore.QSize(40, 40))
        self.voulume_moins_pushButton_5.setObjectName("voulume_moins_pushButton_5")
        self.horizontalLayout.addWidget(self.voulume_moins_pushButton_5)
        self.volume_mute_pushButton_6 = QtWidgets.QPushButton(self.frame_8)
        self.volume_mute_pushButton_6.setMinimumSize(QtCore.QSize(51, 41))
        self.volume_mute_pushButton_6.setMaximumSize(QtCore.QSize(51, 41))
        self.volume_mute_pushButton_6.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: transparent;\n"
"border-color:none;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(199, 199, 199);\n"
"borde-color:none;\n"
"border-radius:10px;\n"
"}")
        self.volume_mute_pushButton_6.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/icons8-no-audio-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.volume_mute_pushButton_6.setIcon(icon8)
        self.volume_mute_pushButton_6.setIconSize(QtCore.QSize(30, 30))
        self.volume_mute_pushButton_6.setObjectName("volume_mute_pushButton_6")
        self.horizontalLayout.addWidget(self.volume_mute_pushButton_6)
        self.volume_plus_pushButton_7 = QtWidgets.QPushButton(self.frame_8)
        self.volume_plus_pushButton_7.setMinimumSize(QtCore.QSize(51, 41))
        self.volume_plus_pushButton_7.setMaximumSize(QtCore.QSize(51, 41))
        self.volume_plus_pushButton_7.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: transparent;\n"
"border-color:none;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(199, 199, 199);\n"
"borde-color:none;\n"
"border-radius:10px;\n"
"}")
        self.volume_plus_pushButton_7.setText("")
        self.volume_plus_pushButton_7.setIcon(icon7)
        self.volume_plus_pushButton_7.setIconSize(QtCore.QSize(40, 40))
        self.volume_plus_pushButton_7.setObjectName("volume_plus_pushButton_7")
        self.horizontalLayout.addWidget(self.volume_plus_pushButton_7)
        self.gridLayout_6.addWidget(self.frame_8, 0, 1, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label = QtWidgets.QLabel(self.frame_9)
        self.label.setMinimumSize(QtCore.QSize(31, 31))
        self.label.setMaximumSize(QtCore.QSize(31, 31))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/icons8-username-48.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.utilisateur_lineEdit = QtWidgets.QLineEdit(self.frame_9)
        self.utilisateur_lineEdit.setMinimumSize(QtCore.QSize(200, 31))
        self.utilisateur_lineEdit.setMaximumSize(QtCore.QSize(300, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.utilisateur_lineEdit.setFont(font)
        self.utilisateur_lineEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QLineEdit:focus{\n"
"\n"
"border-color:2px #3cfff9;\n"
"}")
        self.utilisateur_lineEdit.setText("")
        self.utilisateur_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.utilisateur_lineEdit.setObjectName("utilisateur_lineEdit")
        self.gridLayout_8.addWidget(self.utilisateur_lineEdit, 0, 1, 1, 1)
        self.enregistre_pushButton_8 = QtWidgets.QPushButton(self.frame_9)
        self.enregistre_pushButton_8.setMinimumSize(QtCore.QSize(31, 31))
        self.enregistre_pushButton_8.setMaximumSize(QtCore.QSize(31, 31))
        self.enregistre_pushButton_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.enregistre_pushButton_8.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: transparent;\n"
"border-color:none;\n"
"}\n"
"QPushButton:pressed{\n"
"border-radius:10px;\n"
"    background-color: rgb(203, 203, 203);\n"
"}")
        self.enregistre_pushButton_8.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/icons8-save-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.enregistre_pushButton_8.setIcon(icon9)
        self.enregistre_pushButton_8.setIconSize(QtCore.QSize(25, 25))
        self.enregistre_pushButton_8.setObjectName("enregistre_pushButton_8")
        self.gridLayout_8.addWidget(self.enregistre_pushButton_8, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame_9, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Contact_pushButton_4 = QtWidgets.QPushButton(self.frame_7)
        self.Contact_pushButton_4.setMinimumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Contact_pushButton_4.setFont(font)
        self.Contact_pushButton_4.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/icons8-contact-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Contact_pushButton_4.setIcon(icon10)
        self.Contact_pushButton_4.setIconSize(QtCore.QSize(18, 18))
        self.Contact_pushButton_4.setObjectName("Contact_pushButton_4")
        self.gridLayout_7.addWidget(self.Contact_pushButton_4, 1, 1, 1, 1)
        self.Mores_pushButton_2 = QtWidgets.QPushButton(self.frame_7)
        self.Mores_pushButton_2.setMinimumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Mores_pushButton_2.setFont(font)
        self.Mores_pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/icons8-info-48 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Mores_pushButton_2.setIcon(icon11)
        self.Mores_pushButton_2.setIconSize(QtCore.QSize(18, 18))
        self.Mores_pushButton_2.setObjectName("Mores_pushButton_2")
        self.gridLayout_7.addWidget(self.Mores_pushButton_2, 0, 1, 1, 1)
        self.Commande_pushButton = QtWidgets.QPushButton(self.frame_7)
        self.Commande_pushButton.setMinimumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Commande_pushButton.setFont(font)
        self.Commande_pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/icons8-plus-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Commande_pushButton.setIcon(icon12)
        self.Commande_pushButton.setIconSize(QtCore.QSize(18, 18))
        self.Commande_pushButton.setObjectName("Commande_pushButton")
        self.gridLayout_7.addWidget(self.Commande_pushButton, 0, 0, 1, 1)
        self.About_pushButton_3 = QtWidgets.QPushButton(self.frame_7)
        self.About_pushButton_3.setMinimumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.About_pushButton_3.setFont(font)
        self.About_pushButton_3.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        self.About_pushButton_3.setIcon(icon12)
        self.About_pushButton_3.setIconSize(QtCore.QSize(18, 18))
        self.About_pushButton_3.setObjectName("About_pushButton_3")
        self.gridLayout_7.addWidget(self.About_pushButton_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.frame_7)
        self.pushButton.setMinimumSize(QtCore.QSize(141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton:Hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: rgb(198, 198, 198);\n"
"\n"
"}\n"
"")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/icons8-reload-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon13)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_7.addWidget(self.pushButton, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.frame_7, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.email_pushButton_15.setText(_translate("MainWindow", "Email"))
        self.google_pushButton_14.setText(_translate("MainWindow", "Google"))
        self.face_pushButton_13.setText(_translate("MainWindow", "Facebook"))
        self.pushButton_12.setText(_translate("MainWindow", "Youtube"))
        self.tiktok_pushButton_11.setText(_translate("MainWindow", "TikTok"))
        self.insta_pushButton_10.setText(_translate("MainWindow", "Instagram"))
        self.start_pushButton_9.setText(_translate("MainWindow", "START"))
        self.lampe_pushButton_16.setText(_translate("MainWindow", "Controle des lampes par la main"))
        self.label_4.setText(_translate("MainWindow", "Appuyer sur la touche \"q\" de votre clavier pour arreter le programmer et fermer le par la suite."))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Configurer l\'adresse IP"))
        self.pushButton_17.setText(_translate("MainWindow", "Lampe Salon ON"))
        self.pushButton_18.setText(_translate("MainWindow", "Lampe Salon OFF"))
        self.pushButton_22.setText(_translate("MainWindow", "Lampe Cuisine ON"))
        self.pushButton_19.setText(_translate("MainWindow", "Lampe Cuisine OFF"))
        self.pushButton_23.setToolTip(_translate("MainWindow", "Ce boutton n\'est actuellement pas connecté"))
        self.pushButton_23.setText(_translate("MainWindow", "Non connecté"))
        self.pushButton_24.setToolTip(_translate("MainWindow", "Ce boutton n\'est actuellement pas connecté"))
        self.pushButton_24.setText(_translate("MainWindow", "Non connecté"))
        self.pushButton_27.setToolTip(_translate("MainWindow", "Ce boutton n\'est actuellement pas connecté"))
        self.pushButton_27.setText(_translate("MainWindow", "Non connecté"))
        self.pushButton_26.setToolTip(_translate("MainWindow", "Ce boutton n\'est actuellement pas connecté"))
        self.pushButton_26.setText(_translate("MainWindow", "Non connecté"))
        self.label_5.setText(_translate("MainWindow", "LANC est un programme informatique dit assistant virtuel doté de l\'IA dévelloper et imager par Prince Gildas dans le cadre de sa soutenance cette version si bénéficie de réseau de neurone donc il est plus intélligent"))
        self.label_3.setText(_translate("MainWindow", "Contact"))
        self.label_2.setText(_translate("MainWindow", "@2023 LANC AI version 2.0 | Devellopement Prince Gildas "))
        self.voulume_moins_pushButton_5.setToolTip(_translate("MainWindow", "Volume -"))
        self.volume_mute_pushButton_6.setToolTip(_translate("MainWindow", "volume mute"))
        self.volume_plus_pushButton_7.setToolTip(_translate("MainWindow", "Volume +"))
        self.utilisateur_lineEdit.setPlaceholderText(_translate("MainWindow", "Nom d\'utilisateur"))
        self.Contact_pushButton_4.setText(_translate("MainWindow", "Contact"))
        self.Mores_pushButton_2.setText(_translate("MainWindow", "Mores"))
        self.Commande_pushButton.setText(_translate("MainWindow", "Commande"))
        self.About_pushButton_3.setText(_translate("MainWindow", "About"))
        self.pushButton.setText(_translate("MainWindow", "Acceuil"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
